package: pysense
environment: dev
handlers:
     date:
         arrow_format:  "YYYY/MM/DD"
         default_format:  "YYYY/MM/DD"
         query_format: "YYYY-MM-DD"
     datetime:
         arrow_format: "YYYY/MM/DD HH:mm:ss"
         default_format:  "%%Y/%%m/%%d %%H:%%M:%%S"
logging:
  name: pysense
  level: INFO
  propigate: False
sense:
  username: None
  password: None
  api:
    url: https://api.sense.com/apiservice/api/v1/
    timeout: 5
  realtime:
    url: wss://clientrt.sense.com/monitors/%s/realtimefeed?access_token=%s
sentry:
  enable: True
  dsn:  https://0fc969d48fa04a04a914ba0c4f8172e1@sentry.io/1304672
websocket:
  timeout: 5
